- database/seeders/SupplierSeeder.php
> Add lagi 2

- database/migrations/2025_01_05_201756_create_supplier_pic_phone_table.php
- database/seeders/SupplierSeeder.php
Saya membuat file migration untuk Supplier PIC Phone Number
> Add Migrate Supplier Pic Phone

- database/migrations/2025_01_06_185213_create_supplier_supplier_product_table.php
> Add column id_supplier migrate supplier product

- config/db_constants.php
- database/migrations/2025_01_06_153231_create_category_table.php
- database/seeders/ProductSeeder.php
Mengubah skema tabel category agar bisa mengakomodasi grup dan sub kategori
> refactor:category

- resources/views/dashboard.blade.php
- resources/views/supplier/pic/add.blade.php
- routes/web.php
> Farras d 262 merapikan navbar dashboard dan menambah form tambah pic supplier

- resources/views/dashboard.blade.php
- resources/views/purchase_orders/list.blade.php
- resources/views/supplier/pic/add.blade.php
> Add link action and remove sidebar in list.blade.php

- app/Http/Controllers/PurchaseOrderController.php
- app/Models/PurchaseOrder.php
- app/Models/Supplier.php
- database/skema.sql
- resources/views/purchase_orders/list.blade.php
Menampilkan nama supplier. dan join antar tabel purchase_order dan supplier agar bisa menampilkan nama suppliernya saja
> Join the two tables between purchase order and supplier

- app/Http/Controllers/BranchController.php
- app/Models/Branch.php
- resources/views/branch/list.blade.php
- resources/views/dashboard.blade.php
- resources/views/purchase_orders/list.blade.php
- routes/web.php
Pembuatan view databeles list branch
> View Bracnh list Datables

- resources/views/branch/list.blade.php
> update view ui branch

- app/Http/Controllers/BranchController.php
- resources/views/branch/add.blade.php
- resources/views/branch/list.blade.php
- routes/web.php
- Menambahkan file view resources/views/branch/add.blade.php untuk formulir penambahan cabang baru.
- Mengubah tautan tombol "Tambah" di resources/views/branch/list.blade.php untuk mengarahkan ke rute branch.add.
- Menambahkan rute baru /branch/add di routes/web.php untuk menampilkan view add branch.
> Add route and view for adding a new branch

- app/Models/BomProduction.php
- config/db_constants.php
- database/migrations/2025_03_25_151659_create_bom_production_table.php
- database/seeders/BomProductionSeeder.php
> add:bom production

- app/Models/Category.php
Edit model Category: tambah countCategory
> andika d 237

- app/Http/Controllers/PurchaseOrderController.php
- app/Models/PurchaseOrder.php
menambahkan method searchpurchaseorder di PO Controler
> Rico widiyatma 255 d purchase order controller search purchase order

- app/Http/Controllers/MerkController.php
- app/Models/Merk.php
- routes/web.php
> Rico 174 c merk

- app/Http/Controllers/SupplierController.php
- app/Models/Supplier.php
- routes/web.php
Membuat Fungsi Update Supplier pada Model Supplier dan membuat suppliercontroller
> Membuat supplierController dan Fungsi Update pada model supplier

- app/Models/Product.php
> Telah membuat fungsi menghitung jumlah produk

- resources/views/supplier/detail.blade.php
- routes/web.php
memindahkan main ke development
> Membuat filled form supplier

- app/Http/Controllers/MerkController.php
- resources/views/merk/detail.blade.php
- routes/web.php
> mengerjakan tampilan form yang berisikan data merk

- resources/views/item/add.blade.php
> add form validation 166

- resources/views/supplier/detail.blade.php
- routes/web.php
keterangan : filled form jika dibuka lewat html saja, karena bagian getbyid belum dibuat
> membuat filled form

- app/Http/CategoryController.php
- app/Models/Category.php
> addCategory(CategoryController, Model) Ellen_181

- app/Http/Controllers/ProductController.php
- app/Models/Product.php
> memperbaiki conflig di getProductByID

- resources/views/supplier/pic/add.blade.php
memperbaiki checkbox aktif secara default tercentang dan menyesuaikan sidebar
> memperbaiki checkbox aktif secara default tercentang

- app/Http/Controllers/SupplierController.php
- app/Models/Supplier.php
- routes/web.php
- tests/Feature/UpdateSupplier_Test.php
Sudah saya perbaiki kembali pak
> Update Supplier Model dan Controller

- app/Http/Controllers/SupplierController.php
- app/Models/Supplier.php
- resources/views/supplier/detail.blade.php
- routes/web.php
- tests/Feature/GetSupplierById_Test.php
membuat view berupa filled form supplier dan sudah terhubung dengan model dan controller yang dibuat hadi. saya juga membuat file test untuk getsupplier id, karena saya merubah return json menjadi return ke view. Data pada filled form juga sudah bisa di update dan masuk ke database
view filled form sebelum update (nama perusahaan : PT Korpora Telekomindo TBK) :
view filled form setelah update (TBK nya di hapus) :
test file GetSupplierById_Test.php
> 167 fadiya filled form

- app/Http/Controllers/PurchaseOrderController.php
- app/Models/PurchaseOrder.php
- app/Models/Supplier.php
- resources/views/purchase_orders/list.blade.php
- resources/views/purchase_orders/pdf_report.blade.php
- resources/views/purchase_orders/report_form.blade.php
- routes/web.php
> PDF Purchase Order

- app/Models/Warehouse.php
- tests/Feature/SearchWarehouseTest.php
> Ellen181_searchWarehouse($keyword) + file testing

- app/Models/Warehouse.php
- tests/Feature/DeleteWarehouseModelTest.php
> 196-modelwarehousedelete dan filetest

- resources/views/product/detail.blade.php
di suruh untuk  memodifikasi modelnya agar bisa menampilkan nama lengkap tipe produk
izin pak @ardiansyah-sweng
> raihan-176 menampilkan nama lengkap tipe produk

- app/Http/Controllers/AssortProductionController.php
- routes/web.php
- tests/Feature/SearchProductionControllerTest.php
> Search Production

- app/Http/Controllers/itemController.php
- resources/views/item/detail.blade.php
> Farell 188 Membuat view detail item

- app/Http/Controllers/SupplierMaterialController.php
- app/Models/SupplierMaterial.php
- resources/views/supplier/material/list.blade.php
- resources/views/supplier/material/pdf.blade.php
- routes/web.php
tampilan tombol Cetak Pdf pada setiap supplier
tampilan isi pdf saat berhasil cetak pdf. pada pdf berisi detail seluruh item yang dipasok oleh suplier tersebut
> Cetak PDF seluruh item/material yang dipasok oleh supplier tertentu_Aji prima saputra_2200018213

- app/Http/Controllers/AssortProductionController.php
- routes/web.php
Controller dan Route sudah dibuat dan disesuaikan dari mas joan.
> menambahkan controller dan route

- app/Models/Warehouse.php
- tests/Feature/DeleteWarehouseModelTest.php
…ouse_id di tabel assortment_production.
> 196-menambahkan kondisi di tabel assortment_production.

- app/Models/Merk.php
- tests/Feature/MerkModelTest.php
> MerkModel addMerk()_162

- app/Http/Controllers/BranchController.php
- resources/views/branch/list.blade.php
- routes/web.php
Pull Request Pull raihanraiswicaksono_c_2200018225 sudah saya perbaiki pak
> Menghubungkan button detail ke halaman detail cabang, Environment View (branch/detail.blade.php) (branch/list.blade.php) 

- app/Http/Controllers/WarehouseController.php
- routes/web.php
- tests/Feature/SearchWarehouseTest.php
PR ini menambahkan fungsi baru bernama `searchWarehouse` pada `WarehouseController` untuk menangani permintaan pencarian gudang berdasarkan keyword.
1. **Penambahan Method searchWarehouse**
- Fungsi `searchWarehouse` menerima parameter keyword dari request.
- Menggunakan model `Warehouse` untuk mencari gudang yang sesuai dengan keyword tersebut.
- Jika tidak ditemukan gudang yang sesuai, akan mengembalikan response JSON dengan status 404 dan pesan bahwa data tidak ditemukan.
- Jika ditemukan, akan mengembalikan response JSON dengan flag sukses dan hasil pencarian.
2. **Penambahan Route**
- Mendefinisikan route baru dengan metode **GET** pada URI `/warehouse/search`.
- Route ini akan menjalankan method `searchWarehouse` di `WarehouseController`.
- Route diberi nama `warehouse.search` …
> Menambahkan Function searchWarehouse pada WarehouseController

- app/Http/Controllers/CategoryController.php
- resources/views/category/list.blade.php
- routes/web.php
- tests/Feature/CategorySearchTest.php
Menambahkan fitur pencarian kategori pada CategoryController
Menambahkan unit test untuk pencarian kategori di CategorySearchTest
Menambahkan route GET /category/search
Menambahkan dummy view category/list.blade.php untuk keperluan pengujian
> Search category

- app/Http/Controllers/itemController.php
- resources/views/item/pdf_by_product.blade.php
- routes/web.php
> membuat fungsi cetak pdf pada item berdasarkan product_type tertentu

- app/Models/Category.php
- tests/Feature/SearchCategoryTest.php
> 261 search category

- app/Http/Controllers/BillOfMaterialController.php
- tests/Feature/DeleteBillOfMaterialTest.php
> Controller deleteBillOfMaterial($id)

- app/Http/Controllers/BillOfMaterialController.php
- routes/web.php
- tests/Feature/BillOfMaterialControllerTest.php
> memperbaiki konflik tanpa merubah kode

- app/Http/Controllers/SupplierMaterialController.php
- routes/web.php
- tests/Feature/SupplierMaterialControllerTest.php
> SupplierMaterialController (getSupplierMaterialByProductType)

- app/Http/Controllers/ProductController.php
- tests/Feature/SearchProduct.php
untuk file testnya tetap pakai yg kemarin pak
> Fitur searchProduct fathur284 menggunakan model dari Faiz

- app/Models/SupplierPICModel.php
- tests/Feature/SupplierPICModelTest.php
> SupplierPICModel_209

- app/Http/Controllers/SupplierController.php
- app/Models/Supplier.php
- routes/web.php
- tests/Feature/SupplierSearchTest.php
> Perbaikan Pada Search Supplier By Test

- app/Http/Controllers/CategoryController.php
- resources/views/product/category/detail.blade.php
- routes/web.php
disini saya mendapat akses untuk edit method getcategorybyid (punya alief) dengan uncomment return view
untuk cek bisa lewat root : http://127.0.0.1:8000/category/18
> membuat view detail category dengan  memanggil method getcategorybyid

- app/Models/PurchaseOrder.php
- tests/Feature/PurchaseOrderbySupplierIDTest.php
> GetPurchaseOrderBySupplierID

- app/Models/SupplierMaterial.php
- tests/Feature/CountSupplierMaterialTest.php
membuat count supplier material by type
> membuat count supplier material by type

- app/Http/Controllers/AssortProductionController.php
> memperbaiki controller dan view sudah muncul-171

- app/Http/Controllers/WarehouseController.php
- resources/views/warehouse/filled-form.blade.php
- routes/web.php
> Pembuatan view untuk form filled warehouse (untuk tombol simpan tidak berfungsi karena belum ada fungsi updateWarehouse)

- app/Http/Controllers/WarehouseController.php
- tests/Feature/DeleteWarehouseTest.php
> Memodif controller/deleteWarehouse

- app/Models/Product.php
- tests/Unit/ProductTest.php
Untuk file Testing bisa memanggil dari database, tetapi saya komen pada line 45, karena semua product id terpakai di tabel item, dan saya buat data baru, karena jika pakai data table tidak bisa dihapus karena terpakai semua
> Fauzi 182 deleteproductbyid

- app/Models/PurchaseOrder.php
- tests/Feature/GetPOcountByStatusTest.php
> Jumlah masing masing status PO

- app/Http/Controllers/AssortProductionController.php
- routes/web.php
- tests/Feature/AddAssortProductionTest.php
> Membuat function addProduction() di controller

- app/Http/Controllers/PurchaseOrderController.php
- resources/views/purchase_orders/list.blade.php
pemanggilan model PurchaseOrder::countPurchaseOrder()
ke Controller:
Method getPurchaseOrder() - untuk halaman utama daftar purchase order
Method searchPurchaseOrder() - untuk halaman hasil pencarian
Method getPurchaseOrderByStatus() - untuk halaman filter berdasarkan status
ini ditambahkan pada contoller yang sudah ada biar tidak ada pemanggilan route baru untuk menampilkan data ini, Pak
dan untuk penambahan model pada method controller lain untuk tidak eror saat menampilkan view yang sudah di filter statusnya
> View jumlah purchase order

- app/Http/Controllers/SupplierPIController.php
- routes/web.php
- tests/Feature/GetSupplierPICTest.php
> Sammy c 211

- app/Models/Item.php
- tests/Feature/CountItemByCategoryTest.php
> menghitung jumlah item berdasarkan kategori

- resources/views/bom/list.blade.php
> view display detail BOM

- app/Http/Controllers/BillOfMaterialController.php
- routes/web.php
- tests/Feature/UpdateBillOfMaterialTest.php
> Update Function controller updateBillOfMaterial()

- app/Http/Controllers/SupplierPIController.php
- routes/web.php
- tests/Feature/SupplierPIControllerTest.php
> fadhilah_D SupplierPIController 

- app/Http/Controllers/ProductController.php
- routes/web.php
- tests/Feature/ProductControllerTest.php
- menambahkan fungsi getProductByType($product_type) pada product controller menyelesaikan tugas dari mas Rafi Mahrizky
- fungsi yang saya buat buat sudah memanggil langsung fungsi dari model yang dibuat oleh mas Wisnu
-ini hasilnya :
> getProductByType($product_type)controler

- app/Models/GoodsReceiptNote.php
- tests/Feature/getGoodsReceiptNotesTest.php
- menambahkan fungsi getGoodsReceipNote($po_number) pada model GoodsReceipNote menyelesaikan tugas dari mbak lisya.
- ini untuk hasil testnya:
> getGoodsReceiptNote($po_number)model

- app/Http/Controllers/ProductController.php
- resources/views/product/category/pdf.blade.php
- resources/views/product/list.blade.php
- routes/web.php
> View cetak pdf seluruh produk kategori tertentu

- app/Http/Controllers/SupplierPIController.php
- resources/views/supplier/pic/list.blade.php
- resources/views/supplier/pic/pdfPIC.blade.php
- routes/web.php
Izin mengerjakan lagi pak, apa benar begini? @ardiansyah-sweng
> View cetak pdf seluruh supplier pic berdasarkan supplier

- app/Http/Controllers/SupplierController.php
- app/Models/Supplier.php
- resources/views/supplier/list.blade.php
- routes/web.php
frekuensi order ditambahkan pada tabel supplier list
@ardiansyah-sweng
> puguh_seluruh kolom + frekuensi order ke supplier
